location                  = "francecentral"
resource_group_name       = "rg-incyber-dev"
admin_password            = "P@ssw0rd123!"
admin_username            = "azureuser"
rdp_source_address_prefix = "0.0.0.0/0"